version: "3.8"

services:
  adminBackend:
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
    ports:
      - 7000:7000
      - 7001:7001
      - 9000:9000
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./admin-backend/sql:/docker-entrypoint-initdb.d 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopDB

volumes:
  pgdata:
